from data_loader import Loader
from preprocess import Preprocess

loader = Loader("raw_data")
#train_data, train_labels = loader.read_plutchik_data("primary-plutchik-wheel-DFE.csv")
train_data, train_labels = loader.read_twitter_data("twitter_text_emotion.csv")
#train_data, train_labels = loader.read_biggle("training.1600000.processed.noemoticon.csv")

preprocess = Preprocess(train_data, train_labels)
#preprocess.reduce_by_label(["sadness", "happiness", "hate", "love", "worry"])

clean = preprocess.clean_data()
print(train_data[3])
print(clean[3])
print("")
print(train_data[19])
print(clean[19])
print("")
print(train_data[27])
print(clean[27])
print("")
print(train_data[222])
print(clean[222])
print("")
print(train_data[46])
print(clean[46])
print("")
print(train_data[537])
print(clean[537])
print("")
print(train_data[10240])
print(clean[10240])
print("")
print(train_data[890])
print(clean[890])
print("")