# Generated by Django 2.2.5 on 2019-10-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='post',
            name='songs_from_playlist',
        ),
    ]
